### ISSUE TITLE
BlackOutSystem\variables.hpp bad call fatal error

### ISSUE THREAD

**Issue by gersh99** [X39/Project-Alcatraz#2]
Used Mods
=========
@Project Alcatraz 

Steps to reproduce
==================
1. Launch with Project Alcatraz 
2. Game initializes, Blackscreen, critical error, 

Issues
======
* While step 2: 
include file
x\x39\extensivemedicalsystem\scripting\BlackOutSystem\variables.hpp not found

Additional Notes
================
added a blank variables.hpp to x39_xmed_scripting\BlackOutSystem 
to satisfy the call. but realize the path its looking for isnt actually correct
Unable to find exactly where that call is buried.
![problem](https://user-images.githubusercontent.com/22155572/55661017-607e8400-57d7-11e9-8a7c-6f742e1056b5.PNG)

**Comment by theebu** [comment]
Error only exists in the pre-packed 'x39_xmed_scripting' PBO.
The current version of the file 'x39_xmed_scripting\BlackOutSystem\WakeUnit.sqf' does not contain the error

**Comment by X39** [comment]
PrePacket PBOs should not even be commited, removed them from the repo & added pbos to gitignore
